package cl.codo.fernando.gui;

import cl.codo.fernando.modelo.Usuario;
import cl.codo.fernando.servicio.ServicioDB;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Autentificacion extends javax.swing.JFrame {

    private static Logger logger = LoggerFactory.getLogger(Autentificacion.class);

    /**
     * Creates new form Autentificacion
     */
    public Autentificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rut_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aceptar_boton = new javax.swing.JButton();
        cancelar_boton = new javax.swing.JButton();
        clave_text = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USUARIO");

        jLabel2.setText("RUT");

        rut_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rut_textActionPerformed(evt);
            }
        });
        rut_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rut_textKeyTyped(evt);
            }
        });

        jLabel3.setText("CONTRASEÑA");

        aceptar_boton.setText("Aceptar");
        aceptar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptar_botonMouseClicked(evt);
            }
        });
        aceptar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_botonActionPerformed(evt);
            }
        });

        cancelar_boton.setText("cancelar");
        cancelar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_botonActionPerformed(evt);
            }
        });

        clave_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clave_textActionPerformed(evt);
            }
        });
        clave_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clave_textKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clave_text)
                                    .addComponent(rut_text)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(185, Short.MAX_VALUE)
                        .addComponent(aceptar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(rut_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clave_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rut_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rut_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rut_textActionPerformed

    private void cancelar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_botonActionPerformed

        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_cancelar_botonActionPerformed

    private void aceptar_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptar_botonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptar_botonMouseClicked

    private void aceptar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_botonActionPerformed

        try {
            //chekar si el usuario escrbio el nombre de usuario y pw

            if (rut_text.getText().length() > 0 && clave_text.getText().length() > 0) {
                // Si el usuario si fue validado correctamente
                char[] password;
                password = this.clave_text.getPassword();
                String palabra = new String(password);
                if (validarUsuario(rut_text.getText(), palabra)) //enviar datos a validar
                {
                    // Codigo para mostrar la ventana principal
                    Principal form = new Principal();
                    form.setVisible(true);
                    form.setLocationRelativeTo(null);
                    this.dispose();


                } else {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario y/o contrasenia no son validos.");
                    JOptionPane.showMessageDialog(null, rut_text.getText() + " " + clave_text.getText());
                    rut_text.setText("");    //limpiar campos
                    clave_text.setText("");

                    rut_text.requestFocusInWindow();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Debe escribir nombre de usuario y contrasenia.\n"
                        + "NO puede dejar ningun campo vacio");
            }

        } catch (Exception e) {
            logger.error(e.toString());
            logger.debug("Error en el panel de Autenticación", e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_aceptar_botonActionPerformed

    private void clave_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clave_textActionPerformed
    }//GEN-LAST:event_clave_textActionPerformed

    private void clave_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave_textKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clave_textKeyPressed

    private void rut_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rut_textKeyTyped

        //validar que solo sean numeros y no mas de 8
        char car = evt.getKeyChar();
        if (rut_text.getText().length() >= 8) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_rut_textKeyTyped

    boolean validarUsuario(String elUsr, String elPw) throws IOException {
        boolean resultado = false;
        try {
            Integer rut = Integer.parseInt(elUsr);

            if (rut != null) {
                ServicioDB servicio = new ServicioDB();
                Usuario usuario = servicio.getUsuario(rut);
                resultado = StringUtils.equals(usuario.getClave(), elPw);
            } else {
                logger.info("Usuario '" + elUsr + "' es inválido");
            }
        } catch (Exception e) {
            logger.error(e.toString());
            resultado = false;
        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Autentificacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_boton;
    private javax.swing.JButton cancelar_boton;
    private javax.swing.JPasswordField clave_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField rut_text;
    // End of variables declaration//GEN-END:variables

    private void exit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
